### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by SrikanthKumarC** [Alpha171819/Training-program-management#3]
- [x] Use running subjects table instead of subjects table directly
- [x] Update the subjects periods progress table
the progress table and subjects table data should be used to check the remaining amount of periods of a particular subject
- [x] add a button to save the generated time table to the database, give edit functionality to the generated table.
- [ ] #12
